function patterns = analyze_anomaly_patterns(data, abnormalIdx, normalIdx)
    patterns = struct();
    
    % Calculate basic statistics for abnormal periods
    abnormal_data = data(abnormalIdx, :);
    normal_data = data(normalIdx, :);
    
    patterns.abnormal = struct(...
        'mean', mean(abnormal_data),...
        'std', std(abnormal_data),...
        'min', min(abnormal_data),...
        'max', max(abnormal_data)...
    );
    
    patterns.normal = struct(...
        'mean', mean(normal_data),...
        'std', std(normal_data),...
        'min', min(normal_data),...
        'max', max(normal_data)...
    );
    
    % Calculate deviations
    patterns.deviations = struct(...
        'mean_diff', mean(abnormal_data) - mean(normal_data),...
        'std_ratio', std(abnormal_data) ./ std(normal_data),...
        'range_ratio', (max(abnormal_data) - min(abnormal_data)) ./ (max(normal_data) - min(normal_data))...
    );
end

function stats = analyze_region_stats(data)
    stats = struct(...
        'mean', mean(data),...
        'std', std(data),...
        'percentiles', prctile(data, [25 50 75]),...
        'skewness', skewness(data)...
    );
end

function corr = calculate_correlations(abnormal, normal)
    corr = struct(...
        'abnormal_corr', corrcoef(abnormal),...
        'normal_corr', corrcoef(normal)...
    );
end 