function statistical = analyze_statistical_patterns(data)
    % Calculate basic statistical measures for the time series
    statistical = struct(...
        'mean', mean(data.data),...
        'std', std(data.data),...
        'skewness', skewness(data.data),...
        'kurtosis', kurtosis(data.data),...
        'percentiles', prctile(data.data, [25 50 75])...
    );
end 