function patterns = analyze_anomaly_patterns(data, abnormalIdx, normalIdx)
    % Calculate statistical measures for normal and abnormal regions
    abnormal_data = data(abnormalIdx, :);
    normal_data = data(normalIdx, :);
    
    % Basic statistical analysis
    patterns = struct(...
        'abnormal_stats', struct(...
            'mean', mean(abnormal_data),...
            'std', std(abnormal_data),...
            'min', min(abnormal_data),...
            'max', max(abnormal_data)...
        ),...
        'normal_stats', struct(...
            'mean', mean(normal_data),...
            'std', std(normal_data),...
            'min', min(normal_data),...
            'max', max(normal_data)...
        ),...
        'differences', struct(...
            'mean_diff', mean(abnormal_data) - mean(normal_data),...
            'std_diff', std(abnormal_data) - std(normal_data),...
            'relative_change', (mean(abnormal_data) - mean(normal_data)) ./ mean(normal_data)...
        )...
    );
end

function stats = analyze_region_stats(data)
    stats = struct(...
        'mean', mean(data),...
        'std', std(data),...
        'percentiles', prctile(data, [25 50 75]),...
        'skewness', skewness(data)...
    );
end

function corr = calculate_correlations(abnormal, normal)
    corr = struct(...
        'abnormal_corr', corrcoef(abnormal),...
        'normal_corr', corrcoef(normal)...
    );
end 