function correlations = analyze_correlation_patterns(data)
    % Calculate correlation matrix between all metrics
    correlations = struct(...
        'pearson', corrcoef(data.data),...
        'spearman', corr(data.data, 'Type', 'Spearman'),...
        'kendall', corr(data.data, 'Type', 'Kendall')...
    );
end 