function stats = analyze_region(data)
    stats = struct(...
        'mean', mean(data),...
        'std', std(data),...
        'min', min(data),...
        'max', max(data),...
        'median', median(data),...
        'q1', prctile(data, 25),...
        'q3', prctile(data, 75),...
        'skewness', skewness(data),...
        'kurtosis', kurtosis(data)...
    );
end