function stats = analyze_region(data)
    stats = struct(...
        'mean', mean(data),...
        'std', std(data),...
        'min', min(data),...
        'max', max(data),...
        'skewness', skewness(data),...
        'kurtosis', kurtosis(data)...
    );
end

function corr_matrix = calculate_correlations(data, abnormalIdx, normalIdx)
    % Calculate correlations for abnormal and normal regions
    abnormal_corr = corrcoef(data(abnormalIdx, :));
    normal_corr = corrcoef(data(normalIdx, :));
    
    % Calculate correlation differences
    corr_matrix = struct(...
        'abnormal', abnormal_corr,...
        'normal', normal_corr,...
        'difference', abnormal_corr - normal_corr...
    );
end 