function metrics = extract_performance_metrics(dataset, field_names)
    metrics = struct();
    for i = 1:length(field_names)
        metrics.(field_names{i}) = struct(...
            'mean', mean(dataset.data(:,i)),...
            'std', std(dataset.data(:,i)),...
            'min', min(dataset.data(:,i)),...
            'max', max(dataset.data(:,i)));
    end
end 