function prompt = generate_diagnostic_prompt(metrics, patterns, model_name)
    % Create a structured prompt for diagnostic rule generation
    prompt = sprintf(['Analyze the following database performance metrics and patterns for %s:\n\n', ...
                     'Metrics:\n%s\n\n', ...
                     'Patterns:\n%s\n\n', ...
                     'Generate SQL-like rules that identify performance anomalies. Focus on:\n', ...
                     '1. Significant deviations from normal behavior\n', ...
                     '2. Correlated metric changes\n', ...
                     '3. Temporal patterns\n\n', ...
                     'Format response as JSON with "rules" and "predicates" objects.'], ...
                     model_name, ...
                     jsonencode(metrics), ...
                     jsonencode(patterns));
end 