function prompt = generate_diagnostic_prompt(metrics, patterns, model_name)
    % Create a structured prompt for the LLM to analyze performance patterns
    prompt = sprintf(['Analyze the following database performance metrics and patterns:\n\n' ...
                     'Metrics:\n%s\n\n' ...
                     'Patterns:\n%s\n\n' ...
                     'Based on the above data, please:\n' ...
                     '1. Identify potential performance issues\n' ...
                     '2. Generate diagnostic rules that capture:\n' ...
                     '   - Metric thresholds\n' ...
                     '   - Metric correlations\n' ...
                     '   - Temporal patterns\n' ...
                     '3. Provide confidence scores for each rule\n\n' ...
                     'Format the response as JSON with the following structure:\n' ...
                     '{\n' ...
                     '  "rules": [\n' ...
                     '    {\n' ...
                     '      "name": "rule_name",\n' ...
                     '      "conditions": [...],\n' ...
                     '      "confidence": 0.XX\n' ...
                     '    }\n' ...
                     '  ]\n' ...
                     '}'], ...
                     jsonencode(metrics), ...
                     jsonencode(patterns));
end 