function prompt = generate_diagnostic_prompt(metrics, patterns, model_name)
    prompt = ['Analyze the following database metrics and patterns:\n',...
             'Metrics: ', jsonencode(metrics), '\n',...
             'Patterns: ', jsonencode(patterns), '\n',...
             'Model: ', model_name, '\n\n',...
             'Generate SQL performance diagnostic rules in JSON format with:\n',...
             '1. Conditions based on metric thresholds\n',...
             '2. Confidence scores\n',...
             '3. Clear cause-effect relationships\n'];
end 