function template_rules = load_template_rules()
    % Load predefined template rules for database performance analysis
    template_rules = struct();
    
    % CPU-related rules
    template_rules.cpu = struct(...
        'high_utilization', 'cpu_util > 80',...
        'context_switches', 'context_switches > historical_mean + 2*historical_std',...
        'run_queue_length', 'run_queue > num_cpus * 3'...
    );
    
    % Memory-related rules
    template_rules.memory = struct(...
        'high_usage', 'memory_used > 90% total_memory',...
        'swap_activity', 'swap_in_rate + swap_out_rate > 100/sec',...
        'page_faults', 'page_faults > historical_mean + 3*historical_std'...
    );
    
    % IO-related rules
    template_rules.io = struct(...
        'disk_utilization', 'disk_util > 80',...
        'io_wait', 'io_wait > 20',...
        'throughput', 'io_throughput < historical_mean - 2*historical_std'...
    );
    
    % Network-related rules
    template_rules.network = struct(...
        'packet_loss', 'packet_loss_rate > 1%',...
        'latency', 'network_latency > 100ms',...
        'bandwidth', 'bandwidth_usage > 80% capacity'...
    );
end 