function template_rules = load_template_rules()
    % Load predefined template rules from rules directory
    template_rules = struct();
    
    % Default rules for common performance patterns
    template_rules.cpu = struct(...
        'high_usage', 'CPU utilization > 80%',...
        'low_usage', 'CPU utilization < 20%',...
        'spikes', 'Sudden CPU usage increases > 30%'...
    );
    
    template_rules.memory = struct(...
        'high_usage', 'Memory usage > 90%',...
        'low_free', 'Free memory < 10%',...
        'leaks', 'Steady memory increase over time'...
    );
    
    template_rules.io = struct(...
        'high_wait', 'I/O wait time > 20%',...
        'low_throughput', 'I/O throughput < historical_avg * 0.5',...
        'bottleneck', 'Queue length > 4'...
    );
    
    % Add more template rules as needed
end 