function template_rules = load_template_rules()
    % Load predefined template rules for common database performance issues
    template_rules = struct();
    
    % CPU-bound rules
    template_rules.cpu_bound = struct(...
        'metrics', {'cpu_usage', 'iowait', 'system_load'},...
        'pattern', struct(...
            'cpu_usage', struct('threshold', 80, 'operator', '>'),...
            'iowait', struct('threshold', 20, 'operator', '<')...
        ),...
        'confidence', 0.8...
    );
    
    % IO-bound rules
    template_rules.io_bound = struct(...
        'metrics', {'iowait', 'disk_usage', 'throughput'},...
        'pattern', struct(...
            'iowait', struct('threshold', 40, 'operator', '>'),...
            'disk_usage', struct('threshold', 75, 'operator', '>')...
        ),...
        'confidence', 0.75...
    );
    
    % Memory-bound rules
    template_rules.memory_bound = struct(...
        'metrics', {'memory_usage', 'swap_usage', 'page_faults'},...
        'pattern', struct(...
            'memory_usage', struct('threshold', 90, 'operator', '>'),...
            'swap_usage', struct('threshold', 50, 'operator', '>')...
        ),...
        'confidence', 0.85...
    );
end 